theme = "pkgruv"

[editor]
true-color=true
color-modes=true
jump-label-alphabet="aorisetndhfuvkplwy"
text-width=100
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"

[editor.cursor-shape]
insert="bar"

[editor.lsp]
display-messages=true

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NRML"
mode.insert = "INST"
mode.select = "SLCT"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 1000

# [editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "error"

[keys.normal]
h = "move_line_down"
j = "move_char_left"
"tab" = ":format"
D = "delete_selection_noyank"

[keys.normal.g]
o = "jump_backward"
u = "goto_definition"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
z = ":toggle gutters.line-numbers.min-width 48 3"
l = ["goto_line_end", ":append-output echo ';'"]

[keys.normal.space.t]
t = ":sh zellij run -c -f -x 5% -y 5% --width 90% --height 90% -- bash ~/.config/helix/yazi-picker.sh open"
f = "@:sh zellij run -c -f -x 5% -y 5% --width 90% --height 90% -- bash ~/.config/helix/yazi-picker.sh <C-r>%<C-w> open<ret>"
g = ":sh zellij run -c -f -x 5% -y 5% --width 90% --height 90% -- bash ~/.config/helix/lazygit-picker.sh open"
[keys.insert]
"C-k" = "hover"
# j = { j = "normal_mode" }
